### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @edunham 

lol :-)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/download.servo.org/21)

### CODE REVIEW

**Comment by atouchet** [comment]
@larsbergstrom Can you fix the wording to say "Build" rather than "Builds" while you are at it?

**Comment by larsbergstrom** [comment]
@atouchet Done!

**Comment by edunham** [comment]
Approved of it, bitrotted it, fixed it, pushed it.

**Comment by Manishearth** [comment]
Seems like this hasn't propagated to download.s.o?

**Comment by calexHG** [comment]
@edunham Is it correct to believe that the issue reported bors-servo bot before you means that this is *not* yet a closed issue, and that's why the link still isn't working?

**Comment by Manishearth** [comment]
No, it's fixed in master https://github.com/servo/download.servo.org/blob/master/index.html#L46

**Pull request closed without merging**
