### PR TITLE
Redisable windows builds temporarily

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @jonathandturner

cc @metajack going to wait until keyboard stuff is fixed, hopefully very shortly.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/download.servo.org/26)

### CODE REVIEW

**Comment by sophiajt** [comment]
Sure, wfm

**Comment by edunham** [comment]
Homu would never complete because the .travis.yml previously excluded the auto branch. 

@bors-servo retry

**Pull request merged**
