### PR TITLE
Remove unused dependencies.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by CYBAI** [comment]
@jdm It seems we only use Travis for S3 deployment so I did a quick search and [created a branch](https://github.com/CYBAI/download.servo.org/tree/github-action) for deploying static assets via GitHub action.

Maybe we can move to GitHub Action and entirely remove Travis in this repo 👀?

Ref:
- https://dev.to/johnkevinlosito/deploy-static-website-to-s3-using-github-actions-4a0e
- https://github.com/aws-actions/configure-aws-credentials#usage

**Comment by jdm** [comment]
That looks great!

**Comment by CYBAI** [comment]
Just filed PR with the branch at https://github.com/servo/download.servo.org/pull/76 🙏

**Pull request closed without merging**
